name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx (optional, but recommended)
        uses: docker/setup-buildx-action@v2

      - name: Build base image
        run: |
          docker compose build base

      - name: Build wasm image
        run: |
          docker compose build wasm

      - name: Run build script inside wasm container
        run: |
          # This executes the command specified under "command" in docker-compose.yml
          docker compose run --rm wasm